// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvCAcdEAEqB3jV-IH6emPWF0fCy4oXPxA',
    appId: '1:62303231143:web:b6647010dd914246448f82',
    messagingSenderId: '62303231143',
    projectId: 'chat-app-97b0b',
    authDomain: 'chat-app-97b0b.firebaseapp.com',
    storageBucket: 'chat-app-97b0b.firebasestorage.app',
    measurementId: 'G-6FGXXEF1PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa2nULZp7ZLw2Z66BqQpBAYxgIDR3lGHE',
    appId: '1:62303231143:android:4860043e7835d7a0448f82',
    messagingSenderId: '62303231143',
    projectId: 'chat-app-97b0b',
    storageBucket: 'chat-app-97b0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt70biRt6CSQ1icjzN8zd0nLLr1QoaPKk',
    appId: '1:62303231143:ios:7eae082928aaf654448f82',
    messagingSenderId: '62303231143',
    projectId: 'chat-app-97b0b',
    storageBucket: 'chat-app-97b0b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt70biRt6CSQ1icjzN8zd0nLLr1QoaPKk',
    appId: '1:62303231143:ios:7eae082928aaf654448f82',
    messagingSenderId: '62303231143',
    projectId: 'chat-app-97b0b',
    storageBucket: 'chat-app-97b0b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvCAcdEAEqB3jV-IH6emPWF0fCy4oXPxA',
    appId: '1:62303231143:web:9b1525d3247ec19d448f82',
    messagingSenderId: '62303231143',
    projectId: 'chat-app-97b0b',
    authDomain: 'chat-app-97b0b.firebaseapp.com',
    storageBucket: 'chat-app-97b0b.firebasestorage.app',
    measurementId: 'G-NTB37H3FDC',
  );
}
